// org.zkoss.web.mesg.MWeb.java
//
// Generated by genprop
// DO NOT MODIFY IT MANUALLY. All modifications will be lost.
//
// jumperchen, Fri Sep 17 16:11:45 TST 2010
// Copyright(C) 2001-2008 Potix Corporation. All Rights Reserved.

package org.zkoss.web.mesg;

public interface MWeb extends org.zkoss.mesg.MessageConst {
	static final int MESSAGE_ID = Aide.register(MWeb.class, "msgweb");
	static final int DSP_ACTION_NOT_TERMINATED = 0x5000 + MESSAGE_ID;
	static final int DSP_ACTION_REQUIRED = 0x5001 + MESSAGE_ID;
	static final int DSP_UNKNOWN_ACTION = 0x5002 + MESSAGE_ID;
	static final int DSP_COMMENT_NOT_TERMINATED = 0x5003 + MESSAGE_ID;
	static final int DSP_ATTRIBUTE_VALUE_REQUIRED = 0x5004 + MESSAGE_ID;
	static final int DSP_ATTRIBUTE_VALUE_QUOTE_REQUIRED = 0x5005 + MESSAGE_ID;
	static final int DSP_ATTRIBUTE_INVALID_VALUE = 0x5006 + MESSAGE_ID;
	static final int DSP_ATTRIBUTE_NOT_FOUND = 0x5007 + MESSAGE_ID;
	static final int DSP_TAGLIB_ATTRIBUTE_REQUIRED = 0x5008 + MESSAGE_ID;
	static final int DSP_UNEXPECT_CHARACTER = 0x500a + MESSAGE_ID;
	static final int DSP_EXPECT_CHARACTER = 0x500b + MESSAGE_ID;
	static final int DSP_NESTED_ACTION_NOT_ALLOWED = 0x5010 + MESSAGE_ID;
	static final int DSP_ATTRIBUTE_REQUIRED = 0x5011 + MESSAGE_ID;
	static final int DSP_UNKNOWN_ATTRIBUTE_VALUE = 0x5012 + MESSAGE_ID;
	static final int EL_NOT_TERMINATED = 0x5010 + MESSAGE_ID;
}
