/* TabpanelTag.java

{{IS_NOTE
	Purpose:
		
	Description:
		
	History:
		2007/07/30  09:51:01 , auto generated by Ian Tsai
}}IS_NOTE

Copyright (C) 2007 Potix Corporation. All Rights Reserved.

{{IS_RIGHT
	This program is distributed under GPL Version 2.0 in the hope that
	it will be useful, but WITHOUT ANY WARRANTY.
}}IS_RIGHT
*/
package org.zkoss.jsp.zul;

import org.zkoss.jsp.zul.impl.BranchTag;
import org.zkoss.zk.ui.Component;
import org.zkoss.zul.Tabpanel;

/**
 * The JSP tag of {@link Tabpanel}.
 * @author Ian Tsai
 *
 */
public class TabpanelTag extends BranchTag {

	protected Component newComponent(Class use) throws Exception{
		return (Component) (use==null?new Tabpanel():use.newInstance());
	}

}
