#!/bin/bash
# release
#
#{{IS_NOTE
#	Purpose:
#		
#	Description:
#		
#	History:
#		Mon Nov 14 14:29:09     2005, Created by tomyeh
#}}IS_NOTE
#
#Copyright (C) 2005 Potix Corporation. All Rights Reserved.
#
#{{IS_RIGHT
#	This program is distributed under Lesser GPL Version 2.1 in the hope that
#	it will be useful, but WITHOUT ANY WARRANTY.
#}}IS_RIGHT
#

target=$1

javadocdir=$(grep '^javadoc' build.setting.local)
javadocdir=${javadocdir#javadoc=}
if [ "$javadocdir" = "" ] ; then
	echo javadoc must be specified in $setting
	exit 1
fi
javadocdir=${javadocdir/\~/$HOME}

if [ "$target" == "official" ] ; then
	ver=$(head -1 zul2jsp/version)
	pkgnm=zk-zul2jsp-$ver
elif [ "$target" == "" ] || [ "$target" == "daily" ] ; then
	target=daily

	ver=$(head -1 zul2jsp/version)
	pkgnm=zk-zul2jsp-$ver-$(date +%Y-%m-%d)
else
	echo "Usage: release [ official | daily ]"
	echo Default: daily
	exit 1
fi

rm -rf /tmp/zk
maindir="$(pwd)"

function release0 {
	local prjnm=$1
	local pkgnm=$2
	echo "Release $pkgnm"
	cd $maindir
	mkdir -p /tmp/zk/$pkgnm/dist/lib/ext
	mkdir -p /tmp/zk/$pkgnm/dist/src
	mkdir -p /tmp/zk/$pkgnm/javadoc
	mkdir -p /tmp/zk/$pkgnm/doc
	cp build* /tmp/zk/$pkgnm
	cp -rp bin /tmp/zk/$pkgnm
	cp -rp $prjnm /tmp/zk/$pkgnm
	cp dist/lib/zcommon.jar dist/lib/zweb.jar dist/lib/zk.jar dist/lib/zul.jar dist/lib/$prjnm.jar /tmp/zk/$pkgnm/dist/lib
	cp zkdoc/COPYING /tmp/zk/$pkgnm/doc
	cp zkdoc/zul2jsp-release-note /tmp/zk/$pkgnm/doc/release-note

	if [ "$target" == "timelinez" ] ; then
		cp dist/lib/ext/json_simple.jar /tmp/zk/$pkgnm/dist/lib/ext
	fi

	cd /tmp/zk/$pkgnm
	find -name .svn | xargs rm -rf
	cd $prjnm
	rm -rf codegen debug
	jar cfM $prjnm-sources.jar -C src org
	mv -f $prjnm-sources.jar ../dist/src
	
	cd $javadocdir
	cp -rp $prjnm/* /tmp/zk/$pkgnm/javadoc

	cd /tmp/zk
	echo Output ${pkgnm}.zip
	zip -qr9 ${pkgnm}.zip $pkgnm

	if [ "$target" == "official" ] ; then
		#create maven bundle
		mkdir -p maven
		mkdir -p /tmp/maven
		mv $pkgnm/dist/src/$prjnm-sources.jar maven/$prjnm-$ver-sources.jar
		mv $pkgnm/dist/lib/$prjnm.jar maven/$prjnm-$ver.jar
		sed -e "s/{version}/$ver/" $pkgnm/$prjnm/pom.xml > maven/pom.xml
		echo Output $prjnm-$ver-bundle.jar
		jar cfM $prjnm-$ver-bundle.jar -C maven .
		mv $prjnm-$ver-bundle.jar /tmp/maven

		rm -rf maven
	fi

	rm -rf $pkgnm
}

release0 "zul2jsp" $pkgnm
