/* Utils.java

{{IS_NOTE
	Purpose:
		
	Description:
		
	History:
		Fri Jul 20 19:30:17     2007, Created by tomyeh
}}IS_NOTE

Copyright (C) 2007 Potix Corporation. All Rights Reserved.

{{IS_RIGHT
	This program is distributed under GPL Version 2.0 in the hope that
	it will be useful, but WITHOUT ANY WARRANTY.
}}IS_RIGHT
*/
package org.zkoss.zul.jsp.impl;

import java.util.Collection;
import java.util.Iterator;
import java.util.ArrayList;
import java.io.Writer;
import java.io.IOException;

import org.zkoss.zk.ui.Page;
import org.zkoss.zk.ui.Component;

import org.zkoss.zul.Inline;

/**
 * A utility to be shared by {@link BranchTag} and {@link RootTag} to
 * implement the capability to hold a list of children.
 *
 * @author tomyeh
 */
/*package*/ class Utils {
	private static final String MARK_PREFIX = "<zk~u[", MARK_POSTFIX = "]>";

	/** Adjust the children based the output generated by the inner
	 * tags of {@link BranchTag} (aka., body).
	 *
	 * @param page the page. Specified ony if parent is null (aka. root).
	 * @param parent the parent component. If null, page must be specified.
	 */
	/*package*/ static void adjustChildren(Page page, Component parent,
	Collection children, String body) {
System.out.println("process:\n"+body);
		Iterator it = new ArrayList(children).iterator();
		for (int j = 0, len = body != null ? body.length(): 0; j < len;) {
			int k = body.indexOf(MARK_PREFIX, j);
			String s = (k >= 0 ? body.substring(j, k): body.substring(j)).trim();
			if (s.length() > 0) {
				final Inline inl = new Inline(s);
				if (it.hasNext()) {
					Component child = (Component)it.next();
					parent.insertBefore(inl, child);
				} else {
					parent.appendChild(inl);
				}
			}
		}

		while (it.hasNext())
			((Component)it.next()).detach();
	}
	/** Writes a special mark to the output to represent the component
	 * of the specified child.
	 * The mark is then used by {@link #adjustChildren}
	 */
	/*package*/ static void writeComponentMark(Writer out, Component comp)
	throws IOException {
		out.write(MARK_PREFIX);
		out.write(comp.getUuid());
		out.write(MARK_POSTFIX);
	}
}
