// org.zkoss.zk.mesg.MZk.java
//
// Generated by genprop
// DO NOT MODIFY IT MANUALLY. All modifications will be lost.
//
// jumperchen, Fri Sep 17 16:11:52 TST 2010
// Copyright(C) 2001-2008 Potix Corporation. All Rights Reserved.

package org.zkoss.zk.mesg;

public interface MZk extends org.zkoss.mesg.MessageConst {
	static final int MESSAGE_ID = Aide.register(MZk.class, "msgzk");
	static final int PAGE_NOT_FOUND = 0x1000 + MESSAGE_ID;
	static final int PORTLET_PAGE_REQUIRED = 0x1001 + MESSAGE_ID;
	static final int PAGE_FAILED = 0x1002 + MESSAGE_ID;
	static final int UPDATE_OBSOLETE_PAGE = 0x1010 + MESSAGE_ID;
	static final int RESUME_FAILED = 0x1020 + MESSAGE_ID;
	static final int ILLEGAL_REQUEST_COMPONENT_REQUIRED = 0x2000 + MESSAGE_ID;
	static final int ILLEGAL_REQUEST_WRONG_DATA = 0x2001 + MESSAGE_ID;
	static final int NOT_FOUND = 0x3000 + MESSAGE_ID;
	static final int TOO_MANY_SUSPENDED = 0x3100 + MESSAGE_ID;
	static final int TOO_MANY_REQUESTS = 0x3101 + MESSAGE_ID;
}
