// org.zkoss.zul.mesg.MZul.java
//
// Generated by genprop
// DO NOT MODIFY IT MANUALLY. All modifications will be lost.
//
// jumperchen, Tue, Jun 12, 2012 12:09:03 PM
// Copyright(C) 2001-2008 Potix Corporation. All Rights Reserved.

package org.zkoss.zul.mesg;

public interface MZul extends org.zkoss.mesg.MessageConst {
	static final int MESSAGE_ID = Aide.register(MZul.class, "msgzul");
	static final int EMPTY_NOT_ALLOWED = 0x2000 + MESSAGE_ID;
	static final int NO_POSITIVE_NEGATIVE_ZERO = 0x2001 + MESSAGE_ID;
	static final int NO_POSITIVE_NEGATIVE = 0x2002 + MESSAGE_ID;
	static final int NO_POSITIVE_ZERO = 0x2003 + MESSAGE_ID;
	static final int NO_POSITIVE = 0x2004 + MESSAGE_ID;
	static final int NO_NEGATIVE_ZERO = 0x2005 + MESSAGE_ID;
	static final int NO_NEGATIVE = 0x2006 + MESSAGE_ID;
	static final int NO_ZERO = 0x2007 + MESSAGE_ID;
	static final int NO_FUTURE_PAST_TODAY = 0x2011 + MESSAGE_ID;
	static final int NO_FUTURE_PAST = 0x2012 + MESSAGE_ID;
	static final int NO_FUTURE_TODAY = 0x2013 + MESSAGE_ID;
	static final int NO_FUTURE = 0x2014 + MESSAGE_ID;
	static final int NO_PAST_TODAY = 0x2015 + MESSAGE_ID;
	static final int NO_PAST = 0x2016 + MESSAGE_ID;
	static final int NO_TODAY = 0x2017 + MESSAGE_ID;
	static final int VALUE_NOT_MATCHED = 0x2018 + MESSAGE_ID;
	static final int INTEGER_REQUIRED = 0x2040 + MESSAGE_ID;
	static final int NUMBER_REQUIRED = 0x2041 + MESSAGE_ID;
	static final int DATE_REQUIRED = 0x2042 + MESSAGE_ID;
	static final int OUT_OF_RANGE = 0x2043 + MESSAGE_ID;
	static final int STRING_TOO_LONG = 0x2044 + MESSAGE_ID;
	static final int ILLEGAL_VALUE = 0x2050 + MESSAGE_ID;
	static final int UPLOAD_TITLE = 0x2100 + MESSAGE_ID;
	static final int UPLOAD_MESSAGE = 0x2101 + MESSAGE_ID;
	static final int UPLOAD_CANCEL = 0x2102 + MESSAGE_ID;
	static final int UPLOAD_SUBMIT = 0x2103 + MESSAGE_ID;
	static final int UPLOAD_BROWSE = 0x2104 + MESSAGE_ID;
	static final int UPLOAD_ERROR_EXCEED_MAXSIZE = 0x2105 + MESSAGE_ID;
	static final int OK = 0x2200 + MESSAGE_ID;
	static final int CANCEL = 0x2201 + MESSAGE_ID;
	static final int YES = 0x2220 + MESSAGE_ID;
	static final int NO = 0x2221 + MESSAGE_ID;
	static final int RETRY = 0x2230 + MESSAGE_ID;
	static final int ABORT = 0x2231 + MESSAGE_ID;
	static final int IGNORE = 0x2232 + MESSAGE_ID;
	static final int RELOAD = 0x2233 + MESSAGE_ID;
	static final int FIRST = 0x2300 + MESSAGE_ID;
	static final int LAST = 0x2301 + MESSAGE_ID;
	static final int PREV = 0x2302 + MESSAGE_ID;
	static final int NEXT = 0x2303 + MESSAGE_ID;
	static final int CURRENT = 0x2304 + MESSAGE_ID;
	static final int PLEASE_WAIT = 0x2400 + MESSAGE_ID;
	static final int GRID_GROUP = 0x2500 + MESSAGE_ID;
	static final int GRID_OTHER = 0x2501 + MESSAGE_ID;
	static final int GRID_ASC = 0x2502 + MESSAGE_ID;
	static final int GRID_DESC = 0x2503 + MESSAGE_ID;
	static final int GRID_COLUMNS = 0x2504 + MESSAGE_ID;
	static final int GRID_UNGROUP = 0x2505 + MESSAGE_ID;
	static final int WS_HOME = 0x2600 + MESSAGE_ID;
	static final int WS_PREV = 0x2601 + MESSAGE_ID;
	static final int WS_NEXT = 0x2602 + MESSAGE_ID;
	static final int WS_END = 0x2603 + MESSAGE_ID;
	static final int PANEL_CLOSE = 0x2700 + MESSAGE_ID;
	static final int PANEL_MAXIMIZE = 0x2701 + MESSAGE_ID;
	static final int PANEL_MINIMIZE = 0x2702 + MESSAGE_ID;
	static final int PANEL_EXPAND = 0x2703 + MESSAGE_ID;
	static final int PANEL_COLLAPSE = 0x2704 + MESSAGE_ID;
	static final int PANEL_RESTORE = 0x2705 + MESSAGE_ID;
	static final int CALENDAR_TODAY = 0x2801 + MESSAGE_ID;
	static final int PDFVIEWER_ROTATE_RIGHT = 0x2901 + MESSAGE_ID;
	static final int PDFVIEWER_ROTATE_LEFT = 0x2902 + MESSAGE_ID;
	static final int PDFVIEWER_ZOOM_IN = 0x2903 + MESSAGE_ID;
	static final int PDFVIEWER_ZOOM_OUT = 0x2904 + MESSAGE_ID;
	static final int PDFVIEWER_ZOOM_LEVEL = 0x2905 + MESSAGE_ID;
	static final int PDFVIEWER_ZOOM_FIT_WIDTH = 0x2906 + MESSAGE_ID;
	static final int PDFVIEWER_ZOOM_FIT_HEIGHT = 0x2907 + MESSAGE_ID;
	static final int PDFVIEWER_TOGGLE_FULLSCREEN = 0x2908 + MESSAGE_ID;
	static final int COLORBOX_PALETTE_BUTTON_LABEL = 0x3001 + MESSAGE_ID;
	static final int COLORBOX_PICKER_BUTTON_LABEL = 0x3002 + MESSAGE_ID;
	static final int COLORBOX_COLOR_PALETTE = 0x3003 + MESSAGE_ID;
	static final int COLORBOX_COLOR_PICKER = 0x3004 + MESSAGE_ID;
	static final int COLORBOX_COLOR_R = 0x3005 + MESSAGE_ID;
	static final int COLORBOX_COLOR_G = 0x3006 + MESSAGE_ID;
	static final int COLORBOX_COLOR_B = 0x3007 + MESSAGE_ID;
	static final int COLORBOX_HUE = 0x3008 + MESSAGE_ID;
	static final int COLORBOX_SATURATION = 0x3009 + MESSAGE_ID;
	static final int COLORBOX_VALUE = 0x3010 + MESSAGE_ID;
	static final int COLORBOX_COLOR_HEX = 0x3011 + MESSAGE_ID;
	static final int COLORBOX_COLOR_FIELD = 0x3012 + MESSAGE_ID;
	static final int COLORBOX_COLOR_SPECTRUM_BAR = 0x3013 + MESSAGE_ID;
	static final int COLORBOX_SELECT_COLOR_BUTTON = 0x3014 + MESSAGE_ID;
	static final int COLORBOX_CURRENT_COLOR = 0x3015 + MESSAGE_ID;
	static final int LISTBOX_SELECT_ALL = 0x3101 + MESSAGE_ID;
	static final int NOTIFICATION_INFO = 0x3201 + MESSAGE_ID;
	static final int NOTIFICATION_WARNING = 0x3202 + MESSAGE_ID;
	static final int NOTIFICATION_ERROR = 0x3203 + MESSAGE_ID;
}
