name: Review Trigger WIP
on:
  pull_request_review:
    types: [submitted]

jobs:
  reviw-trigger-wip:
#    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ secrets.ZKADMIN_REBASE_UPDATE_STATUS }}"
        env:
          TOKEN: ${{ secrets.ZKADMIN_REBASE_UPDATE_STATUS }}
      - name: update the status # create the status on the lastest commit sha from pull request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization:  token ${{ secrets.ZKADMIN_REBASE_UPDATE_STATUS }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d '{"state":"success","target_url":"https://github.com/wip/action","description":"ready for review","context":"WIP (action)"}'