// org.zkoss.mesg.MCommon.java
//
// Generated by genprop
// DO NOT MODIFY IT MANUALLY. All modifications will be lost.
//
// jumperchen, Fri Sep 17 16:11:32 TST 2010
// Copyright(C) 2001-2008 Potix Corporation. All Rights Reserved.

package org.zkoss.mesg;

public interface MCommon extends org.zkoss.mesg.MessageConst {
	static final int MESSAGE_ID = Aide.register(MCommon.class, "msgcommon");
	static final int EMPTY_NOT_ALLOWED = 0x1000 + MESSAGE_ID;
	static final int REQUIRED = 0x1001 + MESSAGE_ID;
	static final int ILLEGAL_CHAR = 0x1002 + MESSAGE_ID;
	static final int MESSAGE_CODE_NOT_FOUND = 0x1003 + MESSAGE_ID;
	static final int UNKNOWN_EXCEPTION = 0x1006 + MESSAGE_ID;
	static final int NOT_FOUND = 0x100a + MESSAGE_ID;
	static final int FILE_NOT_FOUND = 0x1200 + MESSAGE_ID;
	static final int FILE_READ_FAILED = 0x1201 + MESSAGE_ID;
	static final int FILE_WRITE_FAILED = 0x1202 + MESSAGE_ID;
	static final int FILE_REMOVE_FAILED = 0x1203 + MESSAGE_ID;
	static final int FILE_OPENING = 0x1204 + MESSAGE_ID;
	static final int FILE_LOADED = 0x1205 + MESSAGE_ID;
	static final int FILE_NOT_FOUND_IGNORED = 0x1206 + MESSAGE_ID;
	static final int FILE_DUPLICATE = 0x1207 + MESSAGE_ID;
	static final int NOT_A_FILE = 0x1208 + MESSAGE_ID;
	static final int FAILED_TO_LOAD = 0x1300 + MESSAGE_ID;
	static final int SERVICE_INIT_OK = 0x1600 + MESSAGE_ID;
	static final int SERVICE_STOP_OK = 0x1601 + MESSAGE_ID;
	static final int SERVICE_INIT_TWICE_NOT_ALLOWED = 0x1603 + MESSAGE_ID;
	static final int CLASS_NOT_COMPATIABLE = 0x1800 + MESSAGE_ID;
	static final int XML_ELEMENT_REQUIRED = 0x2400 + MESSAGE_ID;
	static final int XML_ATTRIBUTE_REQUIRED = 0x2404 + MESSAGE_ID;
	static final int QUOTE_UNMATCHED = 0x2800 + MESSAGE_ID;
	static final int UNEXPECTED_CHARACTER = 0x2801 + MESSAGE_ID;
	static final int EXPECTING_CHARACTER = 0x2802 + MESSAGE_ID;
}
